project:
  type: website

website:
  title: "CSI Math"
  favicon: images/favicons/wavelet.svg
  bread-crumbs: true
  sidebar:
    - title: People
      contents: People
    - title: Undergraduate
      contents: Undergraduate
    - title: ADA Compliance
      contents: ADA
##
  navbar:
    background: primary
    search: false
    collapse-below: "md"
    logo: images/favicons/wavelet.svg
    logo-alt: "CSI Math"
    left:
      - text: "About"
        href: about.qmd
      - text: "Jobs"
        href: jobs.qmd
      - text: "People"
        menu:
          - People/faculty/index.qmd
          - People/staff/index.qmd
      - text: "Undergraduate"
        href: Undergraduate/index.qmd
      - text: "Courses"
        href: Undergraduate/Courses/course_list.qmd
      - text: TEHA
        href: https://www.csi.cuny.edu/academics-and-research/specialized-programs/honors-programs/teacher-education-honors-academy
      - text: Syllabi
        href: Undergraduate/Courses/Syllabi/index.qmd
##
  # announcement:
  #   icon: newspaper
  #   dismissable: true
  #   content: "[Tutoring schedule is up!](Undergraduate/Tutoring)" # Add content here
  #   type: primary
  #   position: below-navbar
  page-footer:
    left: "[CSI Math](/index.html)"

format:
  html:
    theme:
      - cosmo
      - csi-math.scss
    mainfont: Raleway
    grid:
      body-width: 1200px
    toc: false
    css: "https://cdn.jsdelivr.net/gh/ryersondmp/sa11y@4.0.5/dist/css/sa11y.min.css"
    include-in-header:
    - text: |
       <script src="https://cdn.jsdelivr.net/combine/gh/ryersondmp/sa11y@4.0.5/dist/js/lang/en.umd.js,gh/ryersondmp/sa11y@4.0.5/dist/js/sa11y.umd.min.js"></script>
    include-before-body:
    - text: |
        <script>
          Sa11y.Lang.addI18n(Sa11yLangEn.strings);
          const sa11y = new Sa11y.Sa11y({
            checkRoot: "body",
          });
        </script>
